### ISSUE TITLE
Carriage returns are not correctly handled

### ISSUE THREAD

**Issue by JD557** [miyuchina/mistletoe#233] opened 2024-12-07 14:15 UTC
It appears that Mistletoe does not handle `\n` and `\r\n` in the same way.

For example, documents with `\r\n` do not convert lists correctly.

Example:

```python
import mistletoe
from mistletoe import Document

print("With new line")
print(mistletoe.markdown("Markdown test\n\n- list 1\n- list 2\n\ntest"))
print()
print("With new CRLF")
print(mistletoe.markdown("Markdown test\r\n\r\n- list 1\r\n- list 2\r\n\r\ntest"))
```

Output: (Tested with Mistletoe 1.4.0)

```
With new line
<p>Markdown test</p>
<ul>
<li>list 1</li>
<li>list 2</li>
</ul>
<p>test</p>


With new CRLF
<p>Markdown test</p>
<ul>
<li>
<p>list 1</p>
</li>
<li>
<p>list 2</p>
<p>test</p>
</li>
</ul>
```

**Comment by pbodnar** [comment] 2024-12-14 08:59
@JD557, thanks for the report. This is actually the very first duplicate of #64, where the reasons for mistletoe _not_ normalizing spaces are described. Let's continue a potential discussion there. I guess we could at least document the input format expected by mistletoe finally...

**Closed by pbodnar** 2024-12-14 08:59 UTC
