### ISSUE TITLE
Calling children on RawText crashes

### ISSUE THREAD

**Issue by jabdoa2** [miyuchina/mistletoe#31] opened 2018-04-06 13:24 UTC
```
  File "/usr/local/lib/python3.5/dist-packages/mistletoe/span_token.py", line 96, in children
    if isinstance(self._children, GeneratorType):
AttributeError: 'RawText' object has no attribute '_children
```

**Comment by miyuchina** [comment] 2018-04-06 13:35
Hmm, that should be the intended behavior. `RawText` objects only have `RawText.content` attribute, since they are leaf nodes in the parse tree. Could you show me what you were trying to do?

**Comment by jabdoa2** [comment] 2018-04-06 13:58
I just walked the tree using a simple recursive function:

```
def walk(token, level):
  for child in token.children:
     print(level, child)
     walk(child, level + " ")

with open('mydoc.rst, 'r') as f:
    walk(Document(f), " ")
```

I can workaround by checking `hasattr(token, "_children")` but that would not be very nice. In my understanding if a class offers a function if should not crash.

**Comment by miyuchina** [comment] 2018-04-07 20:57
Added the custom exception in 52d7ca32e9ada2558e874cd73589dde318393461.

The visitor pattern implementation I mentioned above:

```python
class Printer(BaseRenderer):
    level = 0

    def render_inner(self, token):
        self.level += 1
        print(self.level * ' ' + str(token))
        for token in token.children:
            self.render(token)
        self.level -= 1

    def render_raw_text(self, token):
        print(self.level * ' ' + str(token))
```

`level` here is managed by a class variable rather than by an additional argument in the recursive call. This is to avoid propagating changes throughout the renderer class. Again, it is clunky, but it works.

@jabdoa2 please let me know if you'd like further discussion on this matter!

**Comment by miyuchina** [comment] 2018-04-15 18:12
Closing for now, but still happy to hear feedback.

**Closed by miyuchina** 2018-04-15 18:12 UTC
Labels: enhancement
