### ISSUE TITLE
Links to URLs ending in brackets are truncated

### ISSUE THREAD

**Issue by DMRobertson** [miyuchina/mistletoe#32] opened 2018-04-10 15:44 UTC
URLs like `https://en.wikipedia.org/wiki/Set_(mathematics)` which end with a bracket seem to get truncated by Mistletoe. It seems to grab a URL by searching for the first `)` character, omitting brackets and any following characters. For instance:

```
$ mistletoe
mistletoe [version 0.5.4] (interactive)
Type Ctrl-D to complete input, or Ctrl-C to exit.
>>> [link](https://en.wikipedia.org/wiki/Set_(mathematics))
... 
<p><a href="https://en.wikipedia.org/wiki/Set_%28mathematics">link</a>)
</p>
```

I'm not sure if this is a serious issue---after all, we can encode the bracket in the URL as `%29`. For what it's worth, GitHub's flavour of markdown seems to be happy with URLs ending in (at least one) bracket. The string `[link](https://en.wikipedia.org/wiki/Set_(mathematics))` results in [link](https://en.wikipedia.org/wiki/Set_(mathematics)), and all is well.

**Comment by miyuchina** [comment] 2018-04-10 16:12
Ah, should be fixed in 2706db3. The problem was caused by a lazy matching character in the regex, because I was trying to solve the problem of multiple links in a paragraph. Disallowing whitespaces (as I should have done from the beginning, derp..) in URLs bypasses this problem.

```
mistletoe [version 0.5.5] (interactive)
Type Ctrl-D to complete input, or Ctrl-C to exit.
>>> [link](https://en.wikipedia.org/wiki/Set_(mathematics))
...
<p><a href="https://en.wikipedia.org/wiki/Set_%28mathematics%29">link</a>
</p>
```

This fix will be included in the next pypi release, so please use the dev branch if you need it working now. Thanks for the bug report!

**Closed by miyuchina** 2018-04-10 16:12 UTC
Labels: bug
