### ISSUE TITLE
Surprising Heading.content

### ISSUE THREAD

**Issue by PatrickMassot** [miyuchina/mistletoe#99] opened 2020-07-01 10:08 UTC
In the following code, I was expecting to see my two titles printed.
```python
from mistletoe import Document                                                            
                                                                                                         
doc = Document("""# My first title                                                        
Some text.                                                                                               
                                                                                          
# My second title                                                                         

Some more text.
""")                                                                                                     
                                                                                          
print(doc.children[0].content, doc.children[2].content)
```
But this prints the second title twice. To get the result I expected, I need to write `print(doc.children[0].children[0].content, doc.children[2].children[0].content)`. I don't know if this is a bug or expected behavior, but I justed wasted half an hour on this.

**Comment by pbodnar** [comment] 2020-07-05 19:58
Hi, this really is the expected behavior. Because by writing `doc.children[0].content` you access a somewhat-private, class-scoped helper property `content` of the Heading class. So yes, accessing the parsed text by `doc.children[0].children[0].content` instead is the correct way.

If you want to know how to access the parsed structure, the best is probably to run mistletoe with the `ASTRenderer` against your markdown text. With this, you'll get a nice tree view of what got parsed:

```json
{
  "type": "Document",
  "footnotes": {},
  "children": [
    {
      "type": "Heading",
      "level": 1,
      "children": [
        {
          "type": "RawText",
          "content": "My first title"
        }
      ]
    },
    {
      "type": "Paragraph",
      "children": [
        {
          "type": "RawText",
          "content": "Some text."
        }
      ]
    },
    {
      "type": "Heading",
      "level": 1,
      "children": [
        {
          "type": "RawText",
          "content": "My second title"
        }
      ]
    },
    {
      "type": "Paragraph",
      "children": [
        {
          "type": "RawText",
          "content": "Some more text."
        }
      ]
    }
  ]
}
```

(BTW You should remove trailing spaces from your example markdown code - or one gets Code blocks parsed otherwise.)

**Comment by PatrickMassot** [comment] 2020-07-05 21:17
Ok, thanks for the explanation. Feel free to close this issue, but I think some more documentation would be helpful here. I don't think it is such an exotic thing to do (I wanted to make the first h1 into the title of the whole thing in some metadata associated to the file).

**Comment by pbodnar** [comment] 2020-07-06 06:59
@PatrickMassot, you're welcome. :) I'm not this project's maintainer though, so I can't close this issue. Anyway, I agree with you this could be documented, probably on the [Contributing](https://github.com/miyuchina/mistletoe/blob/master/CONTRIBUTING.md) page...

**Comment by pbodnar** [comment] 2021-10-30 18:42
Now when I can contribute to the project directly, I added a corresponding chapter _Understanding the AST_ in 14a0d9e85204f9d6b9f3746820658e18dfba5f8d. I hope that could suffice. Suggestions welcome. :)

**Closed by pbodnar** 2021-10-30 18:42 UTC
Labels: question, documentation
