### ISSUE TITLE
URLs seem to prevent code blocks from closing properly

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#24] opened 2018-01-31 10:55 UTC
Hey everyone! I have recently converted a markdown document to Jira format with mistletoe and ran into the following bug. Compiling this document:

    # URL Problem
    ```
    http://google.com/
    ``` 
    this is not part of the code block.

yields this Jira code:

    
    h1. URL Problem
    {code:}
    http://google.com/
    ``` 
    this is not part of the code block.
    {code}

I am not sure why that is.

**Comment by huettenhain** [comment] 2018-01-31 17:49
I  might have found the source for many strange problems I have had with code blocks, including some I hadn't raised yet - I think that the following line:

https://github.com/miyuchina/mistletoe/blob/819c04f7ff6e237df59725bf2ee0136e97efd695/contrib/jira_renderer.py#L136

should be replaced by something like
```python
inner = ''.join(c.content for c in token.children)
```
After all, the contents of a code block should specifically *not* be rendered.

@cctile what do you think? I am not certain enough about this to make it a PR.

**Comment by miyuchina** [comment] 2018-01-31 17:59
I seem to be able to reproduce this issue in HTML renderer as well, so I think the bug might be in the parser.

This is bizarre, though, because I thought I specifically fixed this bug a few commits earlier. I'd need more time to look through this.

**Comment by miyuchina** [comment] 2018-01-31 23:59
Ha I found it! Now I get all the hate towards invisible characters.

So your closing line for the code fence has a space character attached to the end (instead of `~~~\n`, you have `~~~ \n`). The parser is trying to match for `~~~\n` exactly, which is why the code fence just falls off the end.

In 6d3c211 I changed the parsing rule check if `line.startswith("~~~")` instead. It should be working now.

**Closed by miyuchina** 2018-01-31 23:59 UTC
Labels: bug
